### ISSUE TITLE
Wallet not working to confirm in mobile Safari

### ISSUE THREAD

**Issue by baolongt** [dfinity/oisy-wallet#1947]
https://github.com/user-attachments/assets/0f872b01-0d1d-42fa-a288-1c9caa59d75c

**Comment by peterpeterparker** [comment]
Thanks for reaching out and for the video. From Oisy's perspective, there might not be much we can do. The connection between Uniswap and Oisy is established successfully using WalletConnect. In your video, you remain on the "Confirm swap" screen because the focus doesn't return to the tab where Oisy is open. As far as I know, there isn't a web API that allows forcing focus to a tab for good reasons, so resolving this might be challenging. I'll investigate further to ensure I'm not missing anything. Do you know of another browser-based wallet that regains focus in Safari? If so, I can try to compare.

**Comment by baolongt** [comment]
@peterpeterparker I think I don't know any wallet is browser base like Oisy.

Will Oisy wallet will have mobile version?

**Comment by peterpeterparker** [comment]
> The flow work well with my PC

Thanks for the feedback. On your PC does the Oisy tab get the focus automatically or are you manually selecting it?

I'll have a look but, as I said, I doubt there is a solution but, let's see.

> Will Oisy wallet have a mobile version?

No idea.

**Comment by baolongt** [comment]
@peterpeterparker 
Hey I know why, It not jump to Oisy so that why I thought it's a bug

https://github.com/user-attachments/assets/f74d3502-187e-4d51-be9e-9c7f24be3a80

**Comment by baolongt** [comment]
But seems if you have multiple tabs, it gonna use the first tab to show the confirm button
https://github.com/user-attachments/assets/702fb01d-636a-4be7-8b42-aa40525cf1fa

**Comment by peterpeterparker** [comment]
>  It not jump to Oisy so that why I thought it's a bug

Exactly ✅

> But seems if you have multiple tabs, it gonna use the first tab to show the confirm button

That's weird. It looks like it requests a new session in the first tab and send a request for confirmation at the same time. Maybe the state was no clean? I'll try to replicate.

**Comment by baolongt** [comment]
> > It not jump to Oisy so that why I thought it's a bug
> 
> Exactly ✅
> 
> > But seems if you have multiple tabs, it gonna use the first tab to show the confirm button
> 
> That's weird. It looks like it requests a new session in the first tab and send a request for confirmation at the same time. Maybe the state was no clean? I'll try to replicate.

I try to replicate with mobile in the video above but cannot

**Comment by peterpeterparker** [comment]
Thanks a lot for giving it a try and details. I'll try too!

**Comment by peterpeterparker** [comment]
I had a look, and unfortunately, it seems there's not much we can do; it's functioning as expected for a mobile web environment.

Since we've discussed and resolved your question, @baolongt, shall we go ahead and close this issue? Does that work for you?
