### ISSUE TITLE
[BUG] WebSocket connection failed for host: wss://relay.walletconnect.org

### ISSUE THREAD

**Issue by 0xkookoo** [dfinity/oisy-wallet#2078]
**Describe the bug**
An unexpected error happened while trying to connect the wallet. / WebSocket connection failed for host: wss://relay.walletconnect.org

**To Reproduce**

1. Just head to [uniswap.com](https://app.uniswap.org/?lng=en-US)
2. Generate a WalletConnect link
3. Paster the WalletConnect link into oisy.com

**Screenshots**
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/db07163c-135f-4539-8de2-c0acf18aff2c">

<img width="779" alt="image" src="https://github.com/user-attachments/assets/d3929b6a-8f0c-4e4d-a791-8e4dc6bda215">

**Desktop (please complete the following information):**
- OS: MacOS 14.2.1 (23C71)
- Browser: Chrome
- Version: Chrome 127.0.6533.120

**Comment by 0xkookoo** [comment]
I tested the connection at https://piehost.com/websocket-tester, also failed. Seems like it's related with WalletConnect Official?
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/128d3b62-5d67-40c2-9b18-6e52d54b050c">

**Comment by peterpeterparker** [comment]
It works on staging.

<img width="1536" alt="Capture d’écran 2024-08-21 à 12 06 04" src="https://github.com/user-attachments/assets/6f0a7e40-629c-4cbe-a356-99860b5452c3">

**Comment by peterpeterparker** [comment]
The issue has been fixed and a new version that contains the fix - [v0.0.35](https://github.com/dfinity/oisy-wallet/releases/tag/v0.0.35) - has been release in production.

The root cause of the issue was WalletConnect switching from `.org` to `.com` and, given that those new domains were not whitelisted in the Content-Security-Policy, lead Oisy of not being able to connect.

Thanks a lot for reporting the issue!
