### ISSUE TITLE
Make index canister as optional 

### ISSUE THREAD

**Issue by tcpim** [dfinity/oisy-wallet#2883]
**Is your feature request related to a problem? Please describe.**

I love the progress on Oisy! I am confident that Oisy has the potential to be the dominant self custodial wallet in IC ecosystem. For Defi users, it is critical to import any tokens with just the ledger canister because not all tokens have index canister. Say there is a new popular meme token and people want to use Oisy in ICPSwap to trade it, we need to import the token no matter if it has the index canister.

**Describe the solution you'd like**
Just like the new feature in NNS https://www.youtube.com/watch?v=zcXmarBk2L4, Oisy can convey a clear message that without index canister, you won't be able to see the transaction history. 

**Describe alternatives you've considered**

**Additional context**
Congrats on the good work so far! Oisy has a really huge potential, especially with the ability to connect via WalletConnect to connect to the outside world. But first, the most wanted feature in IC right now is a easy to use and reliable self custody wallet for Defi. Plug and Stoic is no longer good. And we need Oisy to take the lead. Thank you!

**Comment by tcpim** [comment]
Also added a forum post here https://forum.dfinity.org/t/can-oisy-support-only-ledger-canister/36185. Thanks!

**Comment by AntonioVentilii-DFINITY** [comment]
@tcpim   Thank you for the suggestion and the praises! Eheh! The entire team (and beyond) is working very hard on the project and it is always good to hear feedbacks!

Regarding the feature, we are including it in our backlog, and we will try to scope it as soon as it we are able to; we will keep you informed

**Comment by tcpim** [comment]
@AntonioVentilii-DFINITY Does Oisy have plan to let IC Dapp to connect to Oisy? Wondering what would be the experience. Do users need to approve/sign when initiate a transfer after connect to Oisy?

**Comment by peterpeterparker** [comment]
> Does Oisy have plan to let IC Dapp to connect to Oisy?

@tcpim Yes, we are currently reviewing the necessary work for this.

> Do users need to approve/sign when initiate a transfer after connect to Oisy?

Yes, the process is similar to the flow you might already be familiar with in other wallets.

On our side, the work is still in progress, and the related library will soon be open-sourced. In the meantime, you can check out [Identity Kit](https://www.identitykit.xyz/), which is a client for the new ICRC standards. These capabilities are being built on top of those standards.

Side note: It’s probably best not to deviate from the original request of this issue, otherwise we might end up with a long thread of various unrelated things. Start a post on the forum or a feature request if you have more quetions. Hope it makes sense.

**Comment by StefanBerger-DFINITY** [comment]
Hi again
I have some news relating tokens w/o index canister.
We are working on this improvement, allowing to have the index canister optional when importing a token. Should be available within the next weeks.
I'll keep you posted.
